### ISSUE TITLE
Update error handling for image and amazon APIs

### ISSUE THREAD

**Issue by eliaahadi** [amazam/amazam#32]

**Comment by maaaashin324** [comment]
This error happens because
1. getResultFromApi function has the counter, but it is declared outside of the function, so this won't be refreshed until the memory reference is deleted by garbage collection.

2. This app uses the asynchronous functions to get and post data. if they work after the components is unmounted, they will try to update unmounted components.

3. In componentDidMount function, a function is called. This function tries to update components, but if they still are not mounted, an unmounted error will happen.

FYI https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

**Comment by maaaashin324** [comment]
SelectedPhoto.js has also an asynchronous function, but it is called only by hitting a button and by this function, navigation works. Therefore unmounting problems don't happen in this class.
